# -*- coding: utf-8 -*-
"""SimilarityAlgo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y4Dt1JAv_shDWDh9GyjeKiVy48ehAG26
"""

from transformers import BertTokenizer, BertModel
import torch
from sklearn.metrics.pairwise import cosine_similarity

# Load pre-trained BERT model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def calculate_semantic_similarity(paragraph1, paragraph2):
    # Tokenize and encode the input paragraphs
    inputs1 = tokenizer(paragraph1, return_tensors='pt', padding=True, truncation=True)
    inputs2 = tokenizer(paragraph2, return_tensors='pt', padding=True, truncation=True)

    # Get the BERT embeddings for both paragraphs
    with torch.no_grad():
        outputs1 = model(**inputs1)
        outputs2 = model(**inputs2)

    # Extract the embeddings for the [CLS] token (representing the entire sequence)
    embeddings1 = outputs1.last_hidden_state[:, 0, :].numpy()
    embeddings2 = outputs2.last_hidden_state[:, 0, :].numpy()

    # Calculate cosine similarity between the embeddings
    similarity_score = cosine_similarity(embeddings1, embeddings2)

    return similarity_score[0][0]

def compare_semantic_similarity(paragraph1, paragraph2, threshold=0.75):
    # Calculate the semantic similarity score
    similarity_score = calculate_semantic_similarity(paragraph1, paragraph2)

    # Check if the similarity score is above the threshold
    if similarity_score >= threshold:
        return "The stories in both paragraphs are similar."
    else:
        return "The stories in both paragraphs are not similar."

# Example usage
paragraph1 = "In the realm of academic capstone projects, students encounter a significant obstacle in the existing project selection and management process. Currently, there is no centralized and efficient platform that seamlessly connects us with suitable projects, making it challenging to navigate and engage meaningfully. The lack of a dedicated Final Year Project portal results in transparency issues, and ineffective communication channels. This situation not only hampers our ability to find and contribute to suitable projects but also affects the overall quality of our learning experience. Addressing these challenges is crucial for ensuring a more effective and enriching FYP project journey."
paragraph2 = "In the realm of academic capstone projects, the current process of project selection, collaboration, and supervision lacks a centralized and efficient platform. Students, faculty, and industry stakeholders often face challenges in seamlessly connecting, communicating, and managing the various aspects of the capstone project lifecycle. This gap hinders the potential for meaningful collaboration, leading to suboptimal project outcomes and a less-than-optimal learning experience for students. The absence of a dedicated and user-friendly Capstone Connect portal results in a lack of transparency in project availability, a cumbersome project matching process, and ineffective communication channels. As a consequence, students may struggle to find suitable projects, faculty may face difficulties in overseeing multiple projects, and industry partners may miss out on opportunities to engage with motivated and capable students. To address these challenges, there is a pressing need for an integrated Capstone Connect portal that streamlines the project selection process, facilitates efficient communication among stakeholders, and enhances the overall management of capstone projects. This portal should serve as a central hub for students, faculty, and industry collaborators, fostering collaboration, transparency, and a more enriching capstone project experience."

result = compare_semantic_similarity(paragraph1, paragraph2)
print(result)