// <auto-generated />
using System;
using CapstoneConnectDatabase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapstoneConnectDatabase.Migrations
{
    [DbContext(typeof(CapstoneConnectContext))]
    partial class CapstoneConnectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNetUserRole", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("RoleId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("UserId", "RoleId");

                b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                b.ToTable("AspNetUserRoles", (string)null);
            });

            modelBuilder.Entity("CapstoneConnect.Models.Administrator", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)");

                b.Property<string>("Email")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Joindate")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("OfficeNo")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Username")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.HasKey("Id");

                b.ToTable("Administrator", (string)null);
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ConcurrencyStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                    .IsUnique()
                    .HasFilter("([NormalizedName] IS NOT NULL)");

                b.ToTable("AspNetRoles");
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetRoleClaim", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                b.ToTable("AspNetRoleClaims");
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("ConcurrencyStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                    .IsUnique()
                    .HasFilter("([NormalizedUserName] IS NOT NULL)");

                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetUserClaim", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                b.ToTable("AspNetUserClaims");
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetUserLogin", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderKey")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                b.ToTable("AspNetUserLogins");
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetUserToken", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens");
            });

            modelBuilder.Entity("CapstoneConnect.Models.FypGroup", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)");

                b.Property<byte>("Aproved")
                    .HasColumnType("tinyint");

                b.Property<DateTime?>("CompletionDate")
                    .HasColumnType("date");

                b.Property<string>("CosupervisorId")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("Cosupervisor_Id");

                b.Property<string>("ProjectDescription")
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<byte>("Status")
                    .HasColumnType("tinyint");

                b.Property<string>("SupervisorId")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("Supervisor_Id");

                b.Property<string>("Tags")
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Year")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.HasKey("Id");

                b.HasIndex("CosupervisorId");

                b.HasIndex("SupervisorId");

                b.ToTable("FypGroup", (string)null);
            });

            modelBuilder.Entity("CapstoneConnect.Models.Meeting", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)");

                b.Property<string>("Agenda")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("GroupId")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Status")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Time")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.HasKey("Id");

                b.ToTable("Meetings");
            });

            modelBuilder.Entity("CapstoneConnect.Models.Notification", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)");

                b.Property<DateTime>("Deadline")
                    .HasColumnType("date");

                b.Property<string>("Details")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<byte>("Semester")
                    .HasColumnType("tinyint");

                b.Property<string>("Title")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.HasKey("Id");

                b.ToTable("Notification", (string)null);
            });

            modelBuilder.Entity("CapstoneConnect.Models.Proposal", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)");

                b.Property<string>("Doc")
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Feedback")
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Member1")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Member1Id")
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("Member1_Id");

                b.Property<string>("Member2")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Member2Id")
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("Member2_Id");

                b.Property<string>("Member3")
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Member3Id")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("Member3_Id");

                b.Property<string>("ProjectDescription")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)")
                    .HasColumnName("Project_Description");

                b.Property<string>("Response")
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Supervisor")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Tags")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Teamlead")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("TeamleadId")
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("Teamlead_Id");

                b.Property<string>("Title")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.HasKey("Id");

                b.ToTable("Proposal", (string)null);
            });

            modelBuilder.Entity("CapstoneConnect.Models.Student", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)");

                b.Property<double>("Cgpa")
                    .HasColumnType("float")
                    .HasColumnName("CGPA");

                b.Property<int>("CompletedCreditHour")
                    .HasColumnType("int")
                    .HasColumnName("Completed_Credit_Hour");

                b.Property<long>("Contact")
                    .HasColumnType("bigint");

                b.Property<string>("Department")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Email")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<DateTime>("EnrollmentDate")
                    .HasColumnType("date");

                b.Property<string>("FypId")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)");

                b.Property<string>("Name")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<int>("Semester")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("FypId");

                b.ToTable("Students");
            });

            modelBuilder.Entity("CapstoneConnect.Models.Submission", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)");

                b.Property<string>("Feedback")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("FypGrpId")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)")
                    .HasColumnName("Fyp_GrpID");

                b.Property<double>("Grade")
                    .HasColumnType("float");

                b.Property<byte>("Status")
                    .HasColumnType("tinyint")
                    .HasColumnName("status");

                b.Property<byte[]>("Time")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.Property<string>("Type")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.HasKey("Id");

                b.ToTable("Submission", (string)null);
            });

            modelBuilder.Entity("CapstoneConnect.Models.Supervisor", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)");

                b.Property<int>("AvailableSlots")
                    .HasColumnType("int")
                    .HasColumnName("Available_Slots");

                b.Property<string>("Department")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Email")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("FypPreferences")
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)")
                    .HasColumnName("FYP_Preferences");

                b.Property<string>("Name")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.HasKey("Id");

                b.ToTable("Supervisor", (string)null);
            });

            modelBuilder.Entity("CapstoneConnect.Models.WorkItem", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime>("AssignedOn")
                    .HasColumnType("date")
                    .HasColumnName("Assigned_On");

                b.Property<string>("Description")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("Feedback")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.Property<string>("FypId")
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("FYP_Id");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)");

                b.Property<string>("StudentId")
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("Student_Id");

                b.Property<string>("Title")
                    .IsRequired()
                    .IsUnicode(false)
                    .HasColumnType("varchar(max)");

                b.HasKey("Id");

                b.ToTable("WorkItems");
            });

            modelBuilder.Entity("AspNetUserRole", b =>
            {
                b.HasOne("CapstoneConnect.Models.AspNetRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CapstoneConnect.Models.AspNetUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetRoleClaim", b =>
            {
                b.HasOne("CapstoneConnect.Models.AspNetRole", "Role")
                    .WithMany("AspNetRoleClaims")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetUserClaim", b =>
            {
                b.HasOne("CapstoneConnect.Models.AspNetUser", "User")
                    .WithMany("AspNetUserClaims")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetUserLogin", b =>
            {
                b.HasOne("CapstoneConnect.Models.AspNetUser", "User")
                    .WithMany("AspNetUserLogins")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetUserToken", b =>
            {
                b.HasOne("CapstoneConnect.Models.AspNetUser", "User")
                    .WithMany("AspNetUserTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("CapstoneConnect.Models.FypGroup", b =>
            {
                b.HasOne("CapstoneConnect.Models.Supervisor", "Cosupervisor")
                    .WithMany("FypGroupCosupervisors")
                    .HasForeignKey("CosupervisorId")
                    .HasConstraintName("FK_FypGroup_Supervisor1");

                b.HasOne("CapstoneConnect.Models.Supervisor", "Supervisor")
                    .WithMany("FypGroupSupervisors")
                    .HasForeignKey("SupervisorId")
                    .HasConstraintName("FK_FypGroup_Supervisor");

                b.Navigation("Cosupervisor");

                b.Navigation("Supervisor");
            });

            modelBuilder.Entity("CapstoneConnect.Models.Student", b =>
            {
                b.HasOne("CapstoneConnect.Models.FypGroup", "Fyp")
                    .WithMany("Students")
                    .HasForeignKey("FypId")
                    .HasConstraintName("FK_Students_FypGroup");

                b.Navigation("Fyp");
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetRole", b =>
            {
                b.Navigation("AspNetRoleClaims");
            });

            modelBuilder.Entity("CapstoneConnect.Models.AspNetUser", b =>
            {
                b.Navigation("AspNetUserClaims");

                b.Navigation("AspNetUserLogins");

                b.Navigation("AspNetUserTokens");
            });

            modelBuilder.Entity("CapstoneConnect.Models.FypGroup", b =>
            {
                b.Navigation("Students");
            });

            modelBuilder.Entity("CapstoneConnect.Models.Supervisor", b =>
            {
                b.Navigation("FypGroupCosupervisors");

                b.Navigation("FypGroupSupervisors");
            });
#pragma warning restore 612, 618
        }
    }
}
